version: "3"
services:

#########################
# SERVERS               #
#########################
  fw-demo-nginx:
    image: nginx
    volumes:
      - ../../www:/usr/share/nginx/html
    ports:
      - 80:80

  fw-demo-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: frontend_weekend
    ports:
      - 5433:5432

